pipeline{
    agent any
    tools{
        maven 'M2_HOME'
    }
    stages{
        stage('clean'){
            steps{
                sh 'mvn clean'
            }
        }
        stage('install'){
            steps{
                sh 'mvn install'
            }
        }
        stage('package'){
            steps{
                sh 'mvn package'
            }
        }
        stage('artfactory'){
            steps{
                sh 'curl -uadmin:AP5Axoc67BTnVfLkWrnbd5yNiuM -T target/bio*.jar "http://18.204.6.73:8081/artifactory/marionprof/profmrn"'
            }
        }
    
       
    }
}